### PR TITLE
Add tables for storing data from other data sources than Lipas

### PR DESCRIPTION
**Pull request by pavetsu14**
Modify databasemodel so that there is a place where to store data from Tampere WFS and museovirasto. Add also metadata table for kooste schema.

### CODE REVIEW

**Comment by pavetsu14** [comment]
Is this OK now?

**Comment by pavetsu14** [comment]
@Rikuoja I changes the names of the kooste schema tables and made a few changes into how ID's are generated (in kooste schema tables luontorastit and metadata) and as a result tests fail again.. I have no idea why. Do you have?

**Comment by pavetsu14** [comment]
@Riku Here is the next version. Did not get the renaming of the constraints to work, but maybe it doesn't matter?

**Review by Rikuoja — APPROVED** [review]
Looks good! I accidentally merged my changes to main before yours, so I will fix the conflicts.

**Pull request merged**
